# -*- mode: ruby -*
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"
	config.vm.define "deploy" do |deploy|
		deploy.vm.hostname = "ceph-deploy.example.com"
		deploy.vm.network "private_network", ip: "192.168.33.40"
		deploy.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "2048"
			vb.name = "ceph-deploy"
		end
		deploy.vm.provision "file", source: "ssh-config", destination: "ssh-config"
	end

	# We provision three nodes to be Ceph servers
	(1..3).each do |i|
		config.vm.define "ceph-node-#{i}" do |config|
			config.vm.hostname = "ceph-node-#{i}.example.com"
			config.vm.network :private_network, ip: "192.168.33.4#{i}"
			config.vm.provider "virtualbox" do |vb|
				vb.cpus = "4"
				vb.memory = "1024"
				vb.name = "ceph-node-#{i}"
			end
	config.vm.provision "shell", inline: <<-SHELL
		mkdir /var/local/osd
		chown -R ceph:ceph /var/local/osd
	SHELL
		end
	end

	config.vm.define "client" do |client|
		client.vm.hostname = "ceph-client.example.com"
		client.vm.network "private_network", ip: "192.168.33.44"
		client.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "2048"
			vb.name = "ceph-client"
		end
	end


	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.
	config.vm.provision "shell", inline: <<-SHELL
		sudo echo redhat | passwd root --stdin
		yum update -y
		yum install bash-completion net-tools vim epel-release ntp ntpdate ntp-doc openssh-server -y
		sudo sed -i 's/#DefaultTimeoutStopSec=90s/DefaultTimeoutStopSec=10s/g' /etc/systemd/system.conf
		sudo yum makecache
		echo "192.168.33.40    ceph-deploy ceph-deploy.example.com" >> /etc/hosts
		echo "192.168.33.41    ceph-node-1 ceph-node-1.example.com" >> /etc/hosts
		echo "192.168.33.42    ceph-node-2 ceph-node-2.example.com" >> /etc/hosts
		echo "192.168.33.43    ceph-node-3 ceph-node-3.example.com" >> /etc/hosts
		echo "192.168.33.44    ceph-client ceph-client.example.com" >> /etc/hosts
		echo "192.168.33.50    openstack-master.example.com" >> /etc/hosts
        echo "192.168.33.51    openstack-node-1.example.com" >> /etc/hosts
		sudo sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/sysconfig/selinux
		sudo setenforce 0
		sudo systemctl disable firewalld
		sudo systemctl stop firewalld
		sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
		sudo systemctl restart sshd
		sudo useradd ceph
		sudo echo ceph | passwd ceph --stdin
		echo "ceph ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/ceph
		sudo chmod 0440 /etc/sudoers.d/ceph
	SHELL
end
