# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

	config.vm.box = "centos/7"

	config.vm.define "master" do |master|
		master.vm.hostname = "kube-master.example.com"
		master.vm.network "private_network", ip: "192.168.73.10"
		master.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "4096"
			vb.name = "kube-master"
		end


	end

	config.vm.define "node1" do |node1|
		node1.vm.hostname = "kube-node-1.example.com"
		node1.vm.network "private_network", ip: "192.168.73.11"
		node1.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "2048"
			vb.name = "kube-node-1"
		end
	end

    config.vm.define "node2" do |node2|
		node2.vm.hostname = "kube-node-2.example.com"
		node2.vm.network "private_network", ip: "192.168.73.12"
		node2.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "2048"
			vb.name = "kube-node-2"
		end
	end

    config.vm.define "node3" do |node3|
		node3.vm.hostname = "kube-node-3.example.com"
		node3.vm.network "private_network", ip: "192.168.73.13"
		node3.vm.provider "virtualbox" do |vb|
			vb.cpus = "4"
			vb.memory = "2048"
			vb.name = "kube-node-3"
		end
	end

	config.vm.provision "file", source: "./kube-install.sh", destination: "kube-install.sh"


	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.
	config.vm.provision "shell", inline: <<-SHELL
        sudo echo redhat | passwd root --stdin
        yum update -y
        yum install bash-completion net-tools vim -y
        echo "192.168.73.5     registry.example.com" >> /etc/hosts
        echo "192.168.73.10    kube-master.example.com" >> /etc/hosts
        echo "192.168.73.11    kube-node-1.example.com" >> /etc/hosts
        echo "192.168.73.12    kube-node-2.example.com" >> /etc/hosts
        echo "192.168.73.13    kube-node-3.example.com" >> /etc/hosts
        echo "192.168.73.40    ceph-deploy ceph-deploy.example.com" >> /etc/hosts
        echo "192.168.73.41    ceph-node-1 ceph-node-1.example.com" >> /etc/hosts
        echo "192.168.73.42    ceph-node-2 ceph-node-2.example.com" >> /etc/hosts
        echo "192.168.73.43    ceph-node-3 ceph-node-3.example.com" >> /etc/hosts
        echo "192.168.73.44    ceph-client ceph-client.example.com" >> /etc/hosts
        echo "192.168.73.50    openstack-master.example.com" >> /etc/hosts
        echo "192.168.73.51    openstack-node-1.example.com" >> /etc/hosts
        sudo chmod +x kube-install.sh
        sudo ./kube-install.sh
        sudo systemctl start cockpit
        sudo systemctl enable cockpit
	SHELL
end
